func.func @perfect_code(%q1: !qu.bit, %q2: !qu.bit, %q3: !qu.bit, %q4: !qu.bit, %q5: !qu.bit) {
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  qref.gate<#qec.perfect> %q1, %q2, %q3, %q4, %q5
  func.return
}
