// RUN: quopt -p randomized-comp %s | filecheck %s

// CHECK:      %q0 = qu.alloc
// CHECK-NEXT: %q1 = qu.alloc
// CHECK-NEXT: %q2 = qu.alloc
// CHECK-NEXT: %0 = prob.uniform : i1
// CHECK-NEXT: %1 = prob.uniform : i1
// CHECK-NEXT: %2 = instrument.constant #gate.id<1>
// CHECK-NEXT: %3 = instrument.constant #gate.x
// CHECK-NEXT: %4 = instrument.constant #gate.z
// CHECK-NEXT: %5 = arith.select %0, %3, %2 : !instrument.type<1>
// CHECK-NEXT: %6 = qssa.dyn_apply<%5> %q0
// CHECK-NEXT: %7 = arith.select %1, %4, %2 : !instrument.type<1>
// CHECK-NEXT: %8 = qssa.dyn_apply<%7> %6
// CHECK-NEXT: %9 = qssa.apply<#gate.h> %8
// CHECK-NEXT: %10 = arith.select %1, %3, %2 : !instrument.type<1>
// CHECK-NEXT: %11 = qssa.dyn_apply<%10> %9
// CHECK-NEXT: %12 = arith.select %0, %4, %2 : !instrument.type<1>
// CHECK-NEXT: %q0_1 = qssa.dyn_apply<%12> %11
// CHECK-NEXT: %13 = prob.uniform : i1
// CHECK-NEXT: %14 = prob.uniform : i1
// CHECK-NEXT: %15 = prob.uniform : i1
// CHECK-NEXT: %16 = prob.uniform : i1
// CHECK-NEXT: %17 = instrument.constant #gate.id<1>
// CHECK-NEXT: %18 = instrument.constant #gate.x
// CHECK-NEXT: %19 = instrument.constant #gate.z
// CHECK-NEXT: %20 = arith.select %13, %18, %17 : !instrument.type<1>
// CHECK-NEXT: %21 = arith.select %14, %18, %17 : !instrument.type<1>
// CHECK-NEXT: %22 = arith.select %15, %19, %17 : !instrument.type<1>
// CHECK-NEXT: %23 = arith.select %16, %19, %17 : !instrument.type<1>
// CHECK-NEXT: %24 = qssa.dyn_apply<%20> %q0_1
// CHECK-NEXT: %25 = qssa.dyn_apply<%22> %24
// CHECK-NEXT: %26 = qssa.dyn_apply<%21> %q1
// CHECK-NEXT: %27 = qssa.dyn_apply<%23> %26
// CHECK-NEXT: %28, %29 = qssa.apply<#gate.cx> %25, %27
// CHECK-NEXT: %30 = qssa.dyn_apply<%22> %28
// CHECK-NEXT: %31 = qssa.dyn_apply<%23> %30
// CHECK-NEXT: %32 = qssa.dyn_apply<%23> %29
// CHECK-NEXT: %33 = qssa.dyn_apply<%20> %32
// CHECK-NEXT: %q0_2 = qssa.dyn_apply<%20> %31
// CHECK-NEXT: %q1_1 = qssa.dyn_apply<%21> %33
// CHECK-NEXT: %34 = prob.uniform : i1
// CHECK-NEXT: %35 = prob.uniform : i1
// CHECK-NEXT: %36 = prob.uniform : i1
// CHECK-NEXT: %37 = prob.uniform : i1
// CHECK-NEXT: %38 = instrument.constant #gate.id<1>
// CHECK-NEXT: %39 = instrument.constant #gate.x
// CHECK-NEXT: %40 = instrument.constant #gate.z
// CHECK-NEXT: %41 = arith.select %34, %39, %38 : !instrument.type<1>
// CHECK-NEXT: %42 = arith.select %35, %39, %38 : !instrument.type<1>
// CHECK-NEXT: %43 = arith.select %36, %40, %38 : !instrument.type<1>
// CHECK-NEXT: %44 = arith.select %37, %40, %38 : !instrument.type<1>
// CHECK-NEXT: %45 = qssa.dyn_apply<%41> %q0_2
// CHECK-NEXT: %46 = qssa.dyn_apply<%43> %45
// CHECK-NEXT: %47 = qssa.dyn_apply<%42> %q2
// CHECK-NEXT: %48 = qssa.dyn_apply<%44> %47
// CHECK-NEXT: %49, %50 = qssa.apply<#gate.cx> %46, %48
// CHECK-NEXT: %51 = qssa.dyn_apply<%43> %49
// CHECK-NEXT: %52 = qssa.dyn_apply<%44> %51
// CHECK-NEXT: %53 = qssa.dyn_apply<%44> %50
// CHECK-NEXT: %54 = qssa.dyn_apply<%41> %53
// CHECK-NEXT: %q0_3 = qssa.dyn_apply<%41> %52
// CHECK-NEXT: %q2_1 = qssa.dyn_apply<%42> %54

%q0 = qu.alloc
%q1 = qu.alloc
%q2 = qu.alloc

%q0_1 = qssa.apply<#gate.h> %q0
%q0_2, %q1_2 = qssa.apply<#gate.cx> %q0_1, %q1
%q0_3, %q2_3 = qssa.apply<#gate.cx> %q0_2, %q2
