name: CI - Pyright

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]

    env:
      PYRIGHT_VERSION: 1.0

    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install project and activate virtual environment
      run: |
        uv sync --all-extras
        source .venv/bin/activate
        echo "$PWD/.venv/bin" >> $GITHUB_PATH

    - name: Pyright
      uses: jakebailey/pyright-action@v2
      with:
        version: PATH
